### ISSUE TITLE
Launch keywriter on the remarkable 2? 

### ISSUE THREAD

**Issue by mpmilano** [dps/remarkable-keywriter#16]
Hi all,

I'm trying to get keywriter to launch on the rm2, but the usual tricks (just assume the toltec-installed one will work vs. download the pre-built binary and LD_PRELOAD the rm2 framebuffer client hack) don't appear to work.  I know others have had more success; what's the trick for this one?

**Comment by briankaemingk** [comment]
Hi,

Did you try it with the framebuffer? That is required for it to work..

https://github.com/ddvk/remarkable2-framebuffer

**Comment by mpmilano** [comment]
Yes, the framebuffer server is running and librm2fb_client.so is preloaded.  I just get a blank white screen.

**Comment by briankaemingk** [comment]
Gotcha, ah now I see that in your original comment. A couple of things to
try..Do you have an empty scratch file in the directory? Can you launch any
other apps?

**Comment by mpmilano** [comment]
I do have an empty file in the editor's storage directory, and all the other apps (installed via toltec) seem to work fine.

**Comment by dps** [comment]
I can replicate this on my rm2 - will take a look

**Comment by mpmilano** [comment]
So my actual issue was with keyboard recognition, so I was seeing the keywriter's default blank screen, not the failure of the app to load.  Though I was surprised that this is how it opens.  @dps you're free to close this issue when you'd like.

**Comment by dps** [comment]
Got it - I appreciate the feedback though, will look at making it more intuitive!

**Comment by Baccanno** [comment]
I tried to connect my Lenovo USB keyboard through a micro usb to usb c cable however it does not seem to be recognized (no green power diod). I'm on rm2 as well, apparently the app launches because I see some artefacts of the screen (rm2fb and keywriter installed through toltec)

Anything I could do to troubleshoot ?
Thanks

**Comment by mpmilano** [comment]
https://github.com/dps/remarkable-keywriter/issues/14 has what you're looking for

**Comment by CrayCJ** [comment]
I'd like to leave this here: https://github.com/dps/remarkable-keywriter/issues/14#issuecomment-1223341129
(Same thread @mpmilano mentions above.)

This discribes in detail how I am able to get a USB A keyboard to work via an usb c to a OTG adapter... Hope this helps!
