### ISSUE TITLE
prebuilt installation

### ISSUE THREAD

**Issue by haizhouus** [dps/remarkable-keywriter#5]
The readme on how to install is not very clear. There is no "edit" under prebuilt, only a binary file "keywriter." When I scp it to /home/root/edit, running keywriter gives a core dump, after ssh into remarkable. I only tried to launch via ssh, just want to check whether it works. BTW, I am on 2.0.1.1 if that is relevant.

**Comment by tetsuosoft** [comment]
did you try renaming all /edit directories to /keywriter instead?

I cant test right now as with reMarkable firmware 2.0,2.0 my SSH isnt working :(

**Comment by Gamithra** [comment]
I've got the same issue - segmentation fault (core dumped) when the keywriter file (fetched from /prebuilt) is run. Any advice?

**Comment by dps** [comment]
I'm working on this now - just upgraded my reMarkable to the latest software and will see if I can get it going again.
